#!/bin/bash
echo "Copying the cgi files (demo,value,distance,hello and counter.txt) to the /usr/lib/cgi-bin/"
sudo cp demo.cgi /usr/lib/cgi-bin/
sudo cp value.cgi /usr/lib/cgi-bin/
sudo cp distance.cgi /usr/lib/cgi-bin/
sudo cp counter.txt /usr/lib/cgi-bin/
sudo cp hello.cgi /usr/lib/cgi-bin/
